name: Deployment CI

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read
    environment:
      name: production
      url: https://cw.recaptime.eu.org
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x
      - name: Run linter and check formating
        run: |
          deno fmt --ignore=.pnp.cjs,.yarn/releases/yarn-3.2.1.cjs
          deno lint --ignore=.pnp.cjs,.yarn/releases/yarn-3.2.1.cjs,package.json
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: recaptime-contentwarnings
          entrypoint: mod.ts
